# Site settings
title: somaye khazaii |سمیه خزاعی
email: hi@hosseinkarami.com
description: توسعه‌دهنده رابط کاربری
baseurl: "https://somayekhazaii.com/"
url: "https://somayekhazaii.com"
twitter: _Karamii
github:  HosseinKarami
behance: HosseinKarami
# Build settings
markdown: kramdown
permalink: pretty
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"
exclude: ["node_modules", "gulpfile.js", "package.json"]
